#!/usr/bin/env python3
"""
Gradio web interface for the course and professor review guide.
Provides a user-friendly interface to ask questions and receive grounded answers.
"""

import os
import gradio as gr
from query import ask


def answer_question(query: str) -> tuple[str, str]:
    """
    Process user query and return grounded answer with sources.
    
    Args:
        query: User's question about courses or professors
    
    Returns:
        Tuple of (answer_text, sources_text) for display
    """
    if not query or not query.strip():
        return (
            "⚠️ Please enter a question about courses, professors, workloads, exam formats, "
            "grading policies, or lecture attendance.",
            ""
        )
    
    # Generate answer using retrieval + LLM
    result = generate(query)
    
    # Format answer section
    answer_text = result['answer']
    if result['error']:
        answer_text = f"⚠️ {answer_text}\n\n*Error: {result['error']}*"
    
    # Format sources section
    sources_text = result['sources']
    
    # Check for hallucinated citations
    if result['citations'].get('invalid_citations'):
        invalid = result['citations']['invalid_citations']
        sources_text += f"\n\n⚠️ **Warning**: LLM referenced sources not in retrieved context: {invalid}"
    
    return answer_text, sources_text


def create_interface() -> gr.Blocks:
    """
    Create and configure the Gradio interface.
    
    Returns:
        Configured Gradio Blocks interface
    """
    with gr.Blocks(title="Course & Professor Review Guide") as demo:
        # Header
        gr.Markdown("""
        # 📚 Course & Professor Review Guide
        
        Ask questions about courses, professors, workloads, exam formats, grading policies, 
        or lecture attendance. Answers are grounded in actual student reviews.
        
        **How it works**: Your question is matched against a database of student reviews 
        using semantic search. The answer is generated by an LLM using only the retrieved 
        reviews — no external knowledge or hallucinations.
        """)
        
        # Input section
        gr.Markdown("## Ask Your Question")
        query_input = gr.Textbox(
            label="Your question",
            placeholder="e.g., 'What do students say about Professor Smith's exams?' or 'How much homework is in CS core classes?'",
            lines=2,
            interactive=True
        )
        
        # Submit button
        submit_btn = gr.Button("Get Answer", variant="primary", size="lg")
        
        # Output section
        gr.Markdown("## Student Reviews Say")
        answer_output = gr.Markdown(
            value="*Your answer will appear here.*",
            label="Answer"
        )
        
        gr.Markdown("## Sources Cited")
        sources_output = gr.Markdown(
            value="*Source list will appear here.*",
            label="Sources"
        )
        
        # Wire up the button
        submit_btn.click(
            fn=answer_question,
            inputs=[query_input],
            outputs=[answer_output, sources_output]
        )
        
        # Allow Enter key to submit
        query_input.submit(
            fn=answer_question,
            inputs=[query_input],
            outputs=[answer_output, sources_output]
        )
        
        # Example queries
        gr.Markdown("## Example Questions")
        gr.Examples(
            examples=[
                "What is the workload for CS core classes?",
                "Which professors are recommended for electives?",
                "What do students say about exam difficulty?",
                "Are lectures mandatory for passing?",
                "What is the grading curve policy?"
            ],
            inputs=[query_input],
            label="Try asking one of these questions"
        )
        
        # Footer
        gr.Markdown("""
        ---
        **How to interpret results:**
        - **Distance score** (in sources): 0 = perfect match, 1+ = weak connection
        - **Sources**: Each source shows which student review was used to ground the answer
        - **⚠️ Warnings**: Flagged if the LLM tried to reference sources not in our database
        
        *This system only answers using actual student reviews. It cannot answer questions 
        about official university policies, dining, housing, or other topics.*
        """)
    
    return demo


def main():
    """Launch the Gradio interface."""
    demo = create_interface()
    demo.launch(
        share=False,  # Local only; set to True to share via public link
        show_error=True
    )


if __name__ == "__main__":
    main()
